#!/usr/bin/env bash

set -euo pipefail

declare -a positional

while [[ $# -gt 0 ]]; do
  case "$1" in
    --) shift; break ;;
    *)
      positional+=("$1");
      ;;
  esac
  shift
done

explain='EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON)'
psql_args=( "$@" )
query_file="${positional[0]}"
query_file_tmp=$(mktemp "${TMPDIR:-/tmp/}explain.XXXXXXXXX")
plan_file_tmp=$(mktemp "${TMPDIR:-/tmp/}plan.XXXXXXXXX")
echo "$explain" >> $query_file_tmp
cat $query_file >> $query_file_tmp
psql --no-psqlrc -qAt -f "$query_file_tmp" "${psql_args[@]}" > $plan_file_tmp
query_sql=$(cat "$query_file")

# Ended up using httpie here instead of curl because curl doesn't support
# passing file as argument for this type of form POST
open $(http -ph --form POST https://explain.dalibo.com/new plan=@"$plan_file_tmp" sql=@"$query_file" \
  | grep Location: \
  | sed 's/Location: //' \
  | tr -d '\r')
