#!/usr/bin/env bash

# Executes the given query sql file, and sends the query plan and run time
# statistics to explain.dalibo.com. Opens result page in browser.
#
# Usage: explain <queryfile.sql> -- <psql args>
# Example: explain query.sql -- 'postgres:://localhost:5432/mydb'

set -euo pipefail

_open() {
  if [ `uname` == "Darwin" ]; then
    open "$1"
  else
    xdg-open "$1"
  fi
}

declare -a positional

while [[ $# -gt 0 ]]; do
  case "$1" in
    --) shift; break ;;
    *)
      positional+=("$1");
      ;;
  esac
  shift
done

explain='EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON)'
psql_args=( "$@" )
query_file="${positional[0]}"
query_file_tmp=$(mktemp "${TMPDIR:-/tmp/}explain.XXXXXXXXX")
plan_file_tmp=$(mktemp "${TMPDIR:-/tmp/}plan.XXXXXXXXX")
echo "$explain" >> $query_file_tmp
cat $query_file >> $query_file_tmp
psql --no-psqlrc -qAt -f "$query_file_tmp" "${psql_args[@]}" > $plan_file_tmp
query_sql=$(cat "$query_file")

# Ended up using httpie here instead of curl because curl doesn't support
# passing file as argument for this type of form POST
_open $(http -ph --form POST https://explain.dalibo.com/new plan=@"$plan_file_tmp" sql=@"$query_file" \
  | grep Location: \
  | sed 's/Location: //' \
  | tr -d '\r')
